### ISSUE TITLE
Bug: When supplying both priv_k and pub_k to Keys(), it returns KeyError

### ISSUE THREAD

**Issue by kforeverisback** [monty888/monstr#10]
Thanks for developing this!
It really helped me understand NIPS and nostr!

I may have found a small bug:

Here is a sample snippet to reproduce the bug:
```python
from monstr import Keys

first = Keys()

second = Keys(priv_k=first.private_key_hex(), pub_k=first.public_key_hex())
## Throws exception here
```

I believe the error is in this line: https://github.com/monty888/monstr/blob/master/src/monstr/encrypt.py#L154

I think the intent was to access `k_pair['pub_k']`, not `k_pair[pub_k]`.

**Comment by monty888** [comment]
Thanks, yes that was the error now fixed
